/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/CreateMirador`; params?: Router.UnknownInputParams; } | { pathname: `/EditProfile`; params?: Router.UnknownInputParams; } | { pathname: `/Explore`; params?: Router.UnknownInputParams; } | { pathname: `/Help`; params?: Router.UnknownInputParams; } | { pathname: `/Login`; params?: Router.UnknownInputParams; } | { pathname: `/MapMiradores`; params?: Router.UnknownInputParams; } | { pathname: `/MiradorDetail`; params?: Router.UnknownInputParams; } | { pathname: `/NotificationSettings`; params?: Router.UnknownInputParams; } | { pathname: `/Notifications`; params?: Router.UnknownInputParams; } | { pathname: `/Privacy`; params?: Router.UnknownInputParams; } | { pathname: `/Profile`; params?: Router.UnknownInputParams; } | { pathname: `/Register`; params?: Router.UnknownInputParams; } | { pathname: `/Settings`; params?: Router.UnknownInputParams; } | { pathname: `/Terms`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/CreateMirador`; params?: Router.UnknownOutputParams; } | { pathname: `/EditProfile`; params?: Router.UnknownOutputParams; } | { pathname: `/Explore`; params?: Router.UnknownOutputParams; } | { pathname: `/Help`; params?: Router.UnknownOutputParams; } | { pathname: `/Login`; params?: Router.UnknownOutputParams; } | { pathname: `/MapMiradores`; params?: Router.UnknownOutputParams; } | { pathname: `/MiradorDetail`; params?: Router.UnknownOutputParams; } | { pathname: `/NotificationSettings`; params?: Router.UnknownOutputParams; } | { pathname: `/Notifications`; params?: Router.UnknownOutputParams; } | { pathname: `/Privacy`; params?: Router.UnknownOutputParams; } | { pathname: `/Profile`; params?: Router.UnknownOutputParams; } | { pathname: `/Register`; params?: Router.UnknownOutputParams; } | { pathname: `/Settings`; params?: Router.UnknownOutputParams; } | { pathname: `/Terms`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/CreateMirador${`?${string}` | `#${string}` | ''}` | `/EditProfile${`?${string}` | `#${string}` | ''}` | `/Explore${`?${string}` | `#${string}` | ''}` | `/Help${`?${string}` | `#${string}` | ''}` | `/Login${`?${string}` | `#${string}` | ''}` | `/MapMiradores${`?${string}` | `#${string}` | ''}` | `/MiradorDetail${`?${string}` | `#${string}` | ''}` | `/NotificationSettings${`?${string}` | `#${string}` | ''}` | `/Notifications${`?${string}` | `#${string}` | ''}` | `/Privacy${`?${string}` | `#${string}` | ''}` | `/Profile${`?${string}` | `#${string}` | ''}` | `/Register${`?${string}` | `#${string}` | ''}` | `/Settings${`?${string}` | `#${string}` | ''}` | `/Terms${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/CreateMirador`; params?: Router.UnknownInputParams; } | { pathname: `/EditProfile`; params?: Router.UnknownInputParams; } | { pathname: `/Explore`; params?: Router.UnknownInputParams; } | { pathname: `/Help`; params?: Router.UnknownInputParams; } | { pathname: `/Login`; params?: Router.UnknownInputParams; } | { pathname: `/MapMiradores`; params?: Router.UnknownInputParams; } | { pathname: `/MiradorDetail`; params?: Router.UnknownInputParams; } | { pathname: `/NotificationSettings`; params?: Router.UnknownInputParams; } | { pathname: `/Notifications`; params?: Router.UnknownInputParams; } | { pathname: `/Privacy`; params?: Router.UnknownInputParams; } | { pathname: `/Profile`; params?: Router.UnknownInputParams; } | { pathname: `/Register`; params?: Router.UnknownInputParams; } | { pathname: `/Settings`; params?: Router.UnknownInputParams; } | { pathname: `/Terms`; params?: Router.UnknownInputParams; };
    }
  }
}
